// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/audio/speech_async': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/audio/speech_async.post').default>>>>
    }
    '/api/audio/speech': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/audio/speech.post').default>>>>
    }
    '/api/audioModels': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/audioModels/index.get').default>>>>
    }
    '/api/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/auth/login.post').default>>>>
    }
    '/api/auth/logout': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/auth/logout.post').default>>>>
    }
    '/api/auth/signup': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/auth/signup.post').default>>>>
    }
    '/api/auth/user': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/auth/user.get').default>>>>
    }
    '/api/chat/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/chat/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/chat/[id].put').default>>>>
    }
    '/api/chat/:id/messages': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/chat/[id]/messages.get').default>>>>
    }
    '/api/chat/merge': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/chat/merge.post').default>>>>
    }
    '/api/chat/messages': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/chat/messages.post').default>>>>
    }
    '/api/chat/sessions': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/chat/sessions.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/chat/sessions.post').default>>>>
    }
    '/api/confirm/respond': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/confirm/respond.post').default>>>>
    }
    '/api/image/generate': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/image/generate.post').default>>>>
    }
    '/api/instruction/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/instruction/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/instruction/[id].put').default>>>>
    }
    '/api/instruction': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/instruction/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/instruction/index.post').default>>>>
    }
    '/api/knowledgebases/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/knowledgebases/[id].delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/knowledgebases/[id].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/knowledgebases/[id].put').default>>>>
    }
    '/api/knowledgebases': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/knowledgebases/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/knowledgebases/index.post').default>>>>
    }
    '/api/learning/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/learning/[id].delete').default>>>>
    }
    '/api/learning/:id/rewrite': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/learning/[id]/rewrite.post').default>>>>
    }
    '/api/learning/batch': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/learning/batch.post').default>>>>
    }
    '/api/learning/cluster': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/learning/cluster.post').default>>>>
    }
    '/api/learning/generate-paragraphs': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/learning/generate-paragraphs.post').default>>>>
    }
    '/api/learning/generate': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/learning/generate.post').default>>>>
    }
    '/api/learning': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/learning/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/learning/index.post').default>>>>
    }
    '/api/learning/search': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/learning/search.get').default>>>>
    }
    '/api/memory/config': {
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/memory/config.put').default>>>>
    }
    '/api/memory': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/memory/index.get').default>>>>
    }
    '/api/memory/ingest': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/memory/ingest.post').default>>>>
    }
    '/api/memory/search': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/memory/search.get').default>>>>
    }
    '/api/models/chat': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/models/chat/index.post').default>>>>
    }
    '/api/models': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/models/index.delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/models/index.get').default>>>>
    }
    '/api/models/pull': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/models/pull/index.post').default>>>>
    }
    '/api/pptx/open': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/pptx/open.get').default>>>>
    }
    '/api/proxy': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/proxy').default>>>>
    }
    '/api/sandbox/summarize': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/sandbox/summarize.post').default>>>>
    }
    '/api/skills/config/:skillName': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/skills/config/[skillName].get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/skills/config/[skillName].put').default>>>>
    }
    '/api/skills': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/skills/index.get').default>>>>
    }
    '/api/skills/marketplace/install': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/skills/marketplace/install.post').default>>>>
    }
    '/api/skills/marketplace/search': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/skills/marketplace/search.get').default>>>>
    }
    '/api/stories/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/stories/[id].delete').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/stories/[id].put').default>>>>
    }
    '/api/stories/:id/audio': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/stories/[id]/audio.delete').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/stories/[id]/audio.post').default>>>>
    }
    '/api/stories/:id/image': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/stories/[id]/image.delete').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/stories/[id]/image.post').default>>>>
    }
    '/api/stories/generate': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/stories/generate.post').default>>>>
    }
    '/api/stories': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/stories/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/stories/index.post').default>>>>
    }
    '/api/stories/mobile/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/stories/mobile/[id].get').default>>>>
    }
    '/api/stories/mobile': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/stories/mobile/index.get').default>>>>
    }
    '/api/stories/mobile/sync': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/stories/mobile/sync.get').default>>>>
    }
    '/api/stories/ollsms': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/stories/ollsms.get').default>>>>
    }
    '/api/test-exec': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../api/test-exec.get').default>>>>
    }
  }
}
export {}